gait_config:
  SLOW:
    freq: 0.3
    amp: 0.3
    coupling: 0.3
    speed_freq_gain: 0.2
    speed_amp_gain: 0.1
    com_z_offset: 0.02
  NORMAL:
    freq: 0.5
    amp: 0.4
    coupling: 0.2
    speed_freq_gain: 0.4
    speed_amp_gain: 0.2
    com_z_offset: 0.0
  TROT:
    freq: 0.8
    amp: 0.5
    coupling: 0.25
    speed_freq_gain: 0.5
    speed_amp_gain: 0.3
    com_z_offset: -0.01
  STEP_IN_PLACE:
    freq: 0.4
    amp: 0.2
    coupling: 0.3
    speed_freq_gain: 0.0
    speed_amp_gain: 0.0
    com_z_offset: 0.01
    lock_torso: true

sim_params:
  init_wait_time: 4.0
  sim_duration: 120.0
  foot_contact_threshold: 1.5
  com_safety_threshold: 0.6
  speed_reduction_factor: 0.5
